import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Check, Search, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";

export type ReelChoice = { id: string; label: string; permalink?: string; thumbnailUrl?: string };
type Reel = { id: string; caption: string | null; permalink: string | null; thumbnailUrl: string | null; timestamp: string | null };

export function ReelSelector({ reels, selected, onSelect }: { reels: Reel[]; selected: ReelChoice | null; onSelect: (reel: ReelChoice) => void }) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const visible = useMemo(() => reels.filter(reel => (reel.caption || "Reel sem legenda").toLowerCase().includes(query.trim().toLowerCase())), [query, reels]);
  const select = (reel: Reel) => { onSelect({ id: reel.id, label: (reel.caption || "Reel sem legenda").slice(0, 255), permalink: reel.permalink || undefined, thumbnailUrl: reel.thumbnailUrl || undefined }); setOpen(false); };
  return <fieldset className="grid min-w-0 gap-3"><legend className="text-sm font-medium leading-none">Escolha o Reel</legend><p className="text-xs leading-5 text-muted-foreground">Abra o seletor para pesquisar e escolher entre os 50 Reels mais recentes da conta.</p><Button type="button" variant="outline" onClick={() => setOpen(true)} className="h-11 min-w-0 max-w-full justify-between overflow-hidden rounded-none border-black text-left"><span className="min-w-0 flex-1 truncate">{selected ? selected.label : "Abrir seletor de Reels"}</span><Search className="ml-3 h-4 w-4 shrink-0" /></Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[92vh] max-w-5xl overflow-y-auto rounded-none border-2 border-black bg-white p-0"><DialogHeader className="border-b border-black p-6"><DialogTitle className="text-3xl font-bold tracking-[-.05em]">Selecionar Reel</DialogTitle><DialogDescription className="pt-2">Pesquise pela legenda ou percorra os Reels recentes. A seleção fica vinculada à automação.</DialogDescription></DialogHeader><div className="sticky top-0 z-10 border-b border-black bg-white p-5"><Input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="Pesquisar pela legenda…" className="rounded-none border-black" /></div><div className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-3">{visible.map(reel => { const label = reel.caption || "Reel sem legenda"; const chosen = selected?.id === reel.id; return <button key={reel.id} type="button" onClick={() => select(reel)} className={chosen ? "relative min-w-0 text-left border-2 border-[#e62222] bg-[#fff7f7]" : "relative min-w-0 text-left border border-black hover:bg-[#f5f5f3]"}>{reel.thumbnailUrl ? <img src={reel.thumbnailUrl} alt="" className="aspect-[9/16] w-full bg-black object-cover" /> : <div className="grid aspect-[9/16] place-items-center bg-black text-white"><Sparkles className="h-5 w-5" /></div>}<div className="min-w-0 p-3"><p className="line-clamp-2 break-words text-sm font-bold">{label}</p><p className="mt-2 text-[10px] uppercase tracking-[.1em] text-muted-foreground">{reel.timestamp ? new Date(reel.timestamp).toLocaleDateString("pt-BR") : "Reel"}</p></div>{chosen && <span className="absolute right-2 top-2 grid h-7 w-7 place-items-center bg-[#e62222] text-white"><Check className="h-4 w-4" /></span>}</button>; })}</div></DialogContent></Dialog></fieldset>;
}
