import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, CheckCircle2, CircleAlert, Clock3, Link2, Plus, Radio, Send, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

function Metric({ label, value, helper, tone = "black" }: { label: string; value: string; helper: string; tone?: "black" | "red" }) {
  return <section className="rule-card min-h-44 p-5"><div className="flex items-start justify-between"><p className="page-kicker">{label}</p><span className={tone === "red" ? "red-square" : "h-3 w-3 border border-black"} /></div><p className="mt-8 text-5xl font-bold leading-none tracking-[-.06em]">{value}</p><p className="mt-3 text-xs leading-5 text-muted-foreground">{helper}</p></section>;
}

export default function Home() {
  const dashboard = trpc.automations.dashboard.useQuery();
  const data = dashboard.data;
  const active = data?.automations.filter(item => item.status === "active").length ?? 0;
  const successful = data?.deliveries.filter(item => item.deliveryStatus === "sent").length ?? 0;
  const failures = data?.deliveries.filter(item => item.deliveryStatus === "failed").length ?? 0;

  return <DashboardLayout><div className="grid-hairline min-h-screen">
    <header className="grid min-h-52 grid-cols-1 border-b border-black px-5 py-7 sm:px-8 lg:grid-cols-12 lg:px-10 lg:py-9">
      <div className="lg:col-span-8"><div className="mb-8 flex items-center gap-3"><span className="red-square" /><p className="page-kicker">Central de operação / 2026</p></div><h1 className="max-w-3xl text-4xl font-bold leading-[.91] tracking-[-.065em] sm:text-6xl">Comentários que chegam. <span className="text-[#e62222]">Links que seguem.</span></h1></div>
      <div className="mt-8 flex flex-col justify-between lg:col-span-4 lg:mt-0 lg:items-end"><p className="max-w-52 text-sm leading-5 text-muted-foreground lg:text-right">Automação de respostas privadas para Reels, limitada a fluxos aprovados.</p><Link href="/automacoes" className="mt-6 inline-flex h-11 items-center justify-center gap-3 border border-black bg-black px-4 text-xs font-bold uppercase tracking-[.12em] text-white transition-colors hover:bg-[#e62222] lg:mt-0">Nova automação <Plus className="h-4 w-4" /></Link></div>
    </header>
    {dashboard.isError && <p role="alert" className="border-b border-black bg-[#fff0f0] px-5 py-3 text-sm font-medium text-[#a91414] sm:px-8 lg:px-10">Não foi possível carregar os dados operacionais. Atualize a página ou tente novamente em instantes.</p>}
    <div className="grid gap-0 border-b border-black md:grid-cols-2 xl:grid-cols-4"><Metric label="Automações ativas" value={dashboard.isLoading ? "—" : String(active).padStart(2, "0")} helper="Apenas fluxos revisados podem ser ativados." /><Metric label="Entregas recentes" value={dashboard.isLoading ? "—" : String(successful).padStart(2, "0")} helper="Respostas privadas enviadas com sucesso." /><Metric label="Exceções" value={dashboard.isLoading ? "—" : String(failures).padStart(2, "0")} helper="Falhas e restrições a revisar." tone={failures > 0 ? "red" : "black"} /><Metric label="Conta conectada" value={dashboard.isLoading ? "—" : data?.accounts.length ? "SIM" : "NÃO"} helper={data?.accounts.length ? `@${data.accounts[0]?.username}` : "Conecte uma conta profissional elegível."} tone={data?.accounts.length ? "black" : "red"} /></div>
    <div className="grid lg:grid-cols-12"><section className="border-b border-black p-5 sm:p-8 lg:col-span-8 lg:border-b-0 lg:border-r lg:p-10"><div className="flex items-end justify-between border-b border-black pb-4"><div><p className="page-kicker">Atividade de entrega</p><h2 className="mt-2 text-2xl font-bold tracking-[-.045em]">Últimos comentários processados</h2></div><Link href="/automacoes" className="hidden text-xs font-bold uppercase tracking-[.1em] underline underline-offset-4 sm:inline">Ver automações</Link></div>
      {dashboard.isLoading ? <div className="py-12 text-sm text-muted-foreground">Carregando atividade…</div> : data?.events.length ? <div className="divide-y divide-black">{data.events.map(event => { const delivery = data.deliveries.find(item => item.webhookEventId === event.id); return <div key={event.id} className="grid gap-3 py-5 sm:grid-cols-[1.2fr_1fr_auto] sm:items-center"><div><p className="text-sm font-bold">{event.commentText || "Comentário sem texto"}</p><p className="mt-1 text-xs text-muted-foreground">ID {event.commentId || "indisponível"}</p>{event.selectedPublicReply && <p className="mt-2 text-xs leading-5 text-muted-foreground">Resposta pública: “{event.selectedPublicReply}”</p>}</div><p className="text-xs text-muted-foreground">{event.processingStatus === "sent" ? "Resposta privada enviada" : event.skipReason || "Em processamento"}</p><span className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.1em]">{delivery?.deliveryStatus === "failed" ? <CircleAlert className="h-4 w-4 text-[#e62222]" /> : <CheckCircle2 className="h-4 w-4" />}{delivery?.deliveryStatus || event.processingStatus}</span></div>; })}</div> : <EmptyActivity />}
    </section><aside className="p-5 sm:p-8 lg:col-span-4 lg:p-10"><p className="page-kicker">Pronto para operar</p><h2 className="mt-2 text-2xl font-bold leading-none tracking-[-.045em]">Sequência de ativação</h2><div className="mt-8 space-y-0 border-t border-black">{[["01", "Conecte o Instagram", "Login direto para contas profissionais."], ["02", "Crie e aprove o fluxo", "Defina o Reel, filtro e resposta."], ["03", "Ative com confiança", "O webhook registra cada resultado."]].map(([number, title, body]) => <div key={number} className="grid grid-cols-[36px_1fr] gap-3 border-b border-black py-5"><span className="text-[10px] font-bold text-[#e62222]">{number}</span><div><h3 className="text-sm font-bold">{title}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{body}</p></div></div>)}</div><Link href="/configuracao" className="mt-7 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.1em] underline underline-offset-4">Abrir guia de configuração <ArrowUpRight className="h-4 w-4" /></Link></aside></div>
  </div></DashboardLayout>;
}

function EmptyActivity() { return <div className="py-12"><div className="flex h-11 w-11 items-center justify-center border border-black"><Radio className="h-5 w-5" /></div><h3 className="mt-5 text-lg font-bold tracking-[-.03em]">Aguardando o primeiro sinal.</h3><p className="mt-2 max-w-md text-sm leading-6 text-muted-foreground">A atividade aparecerá aqui depois que uma automação aprovada for ativada e o webhook receber novos comentários em um Reel escolhido.</p><div className="mt-6 flex flex-wrap gap-4 text-xs font-bold uppercase tracking-[.1em]"><span className="inline-flex items-center gap-2"><ShieldCheck className="h-4 w-4" />Assinatura validada</span><span className="inline-flex items-center gap-2"><Clock3 className="h-4 w-4" />Eventos deduplicados</span><span className="inline-flex items-center gap-2"><Send className="h-4 w-4" />Envio auditável</span></div></div>; }
